# If you do not have OpenSSL installed, update
# the following line to use "http://" instead
source 'https://rubygems.org'

gem "middleman", "~>3.4.0"

# Live-reloading plugin
gem "middleman-livereload", "~> 3.1.0"

# For faster file watcher updates on Windows:
gem "wdm", "~> 0.1.0", :platforms => [:mswin, :mingw]

# Windows does not come with time zone data
gem "tzinfo-data", platforms: [:mswin, :mingw, :jruby]


# javascript plugins
gem "jquery-middleman", "~> 3.1.2"
gem "backstretch-rails", "~> 2.0.4", :require => false
gem "waypoints_rails", "~> 3.0.0", :require => false

# stylesheet plugins
gem "normalize-scss", "~> 3.0.2"
gem "skeleton-rails", "~> 0.1.0", :require => false
gem "font-awesome-sass", "~> 4.4.0"